x = input('Digite algo:')
print('O tipo primitivo deste valor é {}'.format(type(x)))
print('Só tem espaços? {}'.format(x.isspace()))
print('É um numero? {}'.format(x.isalnum()))
print('É alfabetico? {}'.format(x.isalpha()))
print('É alfanumerico? {}'.format(x.isalnum()))
print('Esta em maiusculas? {}'.format(x.isupper()))
print('Esta em minusculas? {}'.format(x.islower()))
print('Está capitalizada? {}'.format(x.istitle()))
